name: flutter_grid_example
description: Flutter Grid UI Example implementation with `dart_grid`. This package allows you to work with data tables like Excel, while saving only real data (empty data is only generated).
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_grid:
    path: ../
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true