name: flutter_grid_ui_example
description: Flutter Grid UI Example implementation with `dart_grid`. This package allows you to work with data tables like Excel, while saving only real data (empty data is only generated).
publish_to: "none"
version: 1.0.0+2

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_grid_ui:
    path: ../
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  collection: ^1.19.1

flutter:
  uses-material-design: true
