name: flutter_grid_ui
description: Flutter Grid UI implementation with `dart_grid`. This package allows you to work with data tables like Excel, while saving only real data (empty data is only generated).
version: 1.0.0+1
repository: https://gitlab.com/dipdev.studio/open-source/flutter-grid

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dart_grid: ^1.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true