name: flutter_grid_ui
description: Flutter Grid UI implementation with `dart_grid`. This package allows you to work with data tables like Excel, while saving only real data (empty data is only generated).
version: 1.0.4
homepage: https://dip.dev
issue_tracker: https://github.com/dip-dev-team/flutter_grid_ui/issues
repository: https://github.com/dip-dev-team/flutter_grid_ui

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  dart_grid: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
